# Change these first
owner: samcsval # Your GitHub organization or username, where this repository lives
repo: upptime # The name of this repository

sites:
  - name: Sam Suite
    url: https://samsuitecs.com
  - name: Sistepago
    url: https://sistepago.xyz
  - name: Sistepago.com
    url: https://sistepago.com
  - name: El Patio de los Corotos
    url: https://elpatiodeloscorotos.com
  - name: Vebella soft
    url: https://vebellasoft.net
  - name: Sam Suite Libro Compras 
    url: https://lc.samsuitecs.com
  - name: Sam Suite Fuerza de ventas SMXII 
    url: https://smxxi.samsuitecs.com
  - name: Logistic Service
    url: https://sistepago.xyz/samlogisticservice/odata/Vehiculos
  - name: Logistic Frontend
    url: https://logistic.sistepago.xyz/
assignees:
  - samcsval
status-website:
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
  #cname: demo.upptime.js.org
  baseUrl: /upptime
  logoUrl: https://lc.samsuitecs.com/logo.png
  name: Sam Suite Status
  introTitle: "**Sam Suite Status Systems** permite monitorear todos nuestros servicios y páginas. De tal manera de informar a nuestros clientes el status de nuestros servidores."
  introMessage: Sam Suite siempre en la busqueda de mejorar la experiencia de nuetros clientes, implementó esta página donde se monitorean nuestros diferentes servicios, sitios hospedados y clientes atendidos, de tal forma que puedan en cualquier momento visualizar el estatus de sus servicios.
  navbar:
    - title: Status
      href: /upptime
    - title: Sam Suite
      href: https://samsuitecs.com
    - title: Sam Suite Libro de Compra
      href: https://lc.samsuitecs.com

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
